// For later use
export const SEARCH_TYPING = 'SEARCH_TYPING';

// Currently used
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const INIT_MOVIES = 'INIT_MOVIES';
export const INIT_MOVIES_SUCCESS = 'INIT_MOVIES_SUCCESS';
export const INIT_MOVIES_ERROR = 'INIT_MOVIES_ERROR';

export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const REQUEST_GENRES = 'REQUEST_GENRES';
export const RECEIVE_GENRES_SUCCESS = 'RECEIVE_GENRES_SUCCESS';

export const SAVE_GENRES_SUCCESS = 'SAVE_GENRES_SUCCESS';
export const SAVE_GENRES_ERROR = 'SAVE_GENRES_ERROR';
export const SAVE_MOVIE_SUCCESS = 'SAVE_MOVIE_SUCCESS';
export const REMOVE_MOVIE_SUCCESS = 'REMOVE_MOVIE_SUCCESS';

export const FETCH_WATCHLIST = 'FETCH_WATCHLIST';
export const FETCH_WATCHLIST_SUCCESS = 'FETCH_WATCHLIST_SUCCESS';

export const CHANGE_TAB = 'CHANGE_TAB';

export const FETCH_CREDITS = 'FETCH_CREDITS';
export const FETCH_CREDITS_SUCCESS = 'FETCH_CREDITS_SUCCESS';
export const FETCH_CREDITS_ERROR = 'FETCH_CREDITS_ERROR';

export const FETCH_RECOMMENDATIONS_SUCCESS = 'FETCH_RECOMMENDATIONS_SUCCESS';
export const FETCH_RECOMMENDATIONS = 'FETCH_RECOMMENDATIONS';
